spring.application.name=platform-cicd-api

server.port=${SERVER_PORT:8082}

management.endpoints.web.exposure.include=health,info

platform.gitops.values-path=${PLATFORM_GITOPS_VALUES_PATH:../platform-deploy/environments/dev/values.yaml}
